FROM node

RUN apt-get update && apt-get -y upgrade
RUN apt-get install net-tools vim
RUN npm i -g grpcnode
# git clone https://github.com/konsumer/grpcnode.git
RUN npm install -g grpcc
# git clone https://github.com/njpatel/grpcc.git

